version: '2.14'

services:
  service:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: service
    volumes:
      - ./var/www/images:/opt/pics:rw
      - ./var/www/files:/opt/files:rw
    depends_on:
      - postgres
      - webp

  postgres:
    image: postgres:latest
    volumes:
      - ./db/data.sql:/docker-entrypoint-initdb.d/data.sql
      - /var/local/db/docker/:/var/lib/postgresql/data
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=docker
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped

  webp:
    image: webpsh/webp-server-go
    restart: unless-stopped
    volumes:
      - ./var/www/images:/opt/pics:rw
      - ./var/www/cache:/opt/exhaust:rw
    ports:
      - "3333:3333"
